import { writeFileSync, existsSync, mkdirSync, readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { randomBytes } from 'node:crypto';
import { readBrand, REPO_ROOT, appDir } from '../lib/paths.mjs';
import { validate } from '../../../packages/brand/src/validate.mjs';
import { ensureDocker } from '../lib/docker.mjs';
import { run } from '../lib/run.mjs';
import { parseEnvFile } from './secrets.mjs';
import { parseJsonc } from '../lib/render.mjs';
import { seed } from './seed.mjs';

/**
 * The wrangler config the local stack runs against.
 *
 * Runtime settings come from the deployment template rather than being
 * repeated, so the two cannot drift — which they did: the Worker's entry
 * point moved and this kept naming the old path.
 */
export function localWranglerConfig({ slug, adminPort, template, adminDevBypass }) {
	const body = {
		$schema: template.$schema,
		name: `${slug}-api-local`,
		main: template.main,
		compatibility_date: template.compatibility_date,
		compatibility_flags: template.compatibility_flags,
		d1_databases: [{
			binding: 'DB',
			database_name: `${slug}-db-local`,
			// Local only: wrangler --local never reaches Cloudflare, so this
			// id names nothing real.
			database_id: 'local',
			migrations_dir: 'migrations',
		}],
		vars: {
			ADMIN_ALLOWED_ORIGINS: `http://localhost:${adminPort},http://127.0.0.1:${adminPort}`,
			// wrangler dev --local does not forward the launching process's own
			// env into the Worker's bindings — only `vars` here does that. This
			// was set solely in docker/.env, which reaches the API container's
			// process.env but never the Worker, so the admin bypass was always
			// undefined and every admin request 501'd.
			ADMIN_DEV_BYPASS: adminDevBypass,
		},
	};
	return (
		'// Generated by `churchkit dev` on every run — edits here are lost.\n' +
		'// Local development only; it reaches no Cloudflare account.\n' +
		JSON.stringify(body, null, '\t') + '\n'
	);
}

/** A flags map with extra switches turned on, for delegating to another command. */
function withFlags(flags, extra) {
	const next = new Map(flags);
	for (const key of extra) next.set(key, true);
	next.has = Map.prototype.has.bind(next);
	return next;
}

/**
 * Poll the API's own health endpoint until it answers.
 *
 * The first run installs the whole workspace inside the container, which
 * takes minutes — so this waits generously and says what it is waiting for,
 * rather than failing on a timeout that looks like a broken setup.
 */
async function waitForApi(port, timeoutMs = 5 * 60 * 1000) {
	const deadline = Date.now() + timeoutMs;
	while (Date.now() < deadline) {
		try {
			const res = await fetch(`http://127.0.0.1:${port}/api/capabilities`);
			if (res.ok) return true;
		} catch {}
		await new Promise((r) => setTimeout(r, 3000));
	}
	return false;
}

const DOCKER_DIR = resolve(REPO_ROOT, 'docker');

/**
 * Run the whole stack locally in containers, so someone can see ChurchKit
 * working before buying a domain or creating a Cloudflare account.
 *
 * Everything is local: workerd via wrangler, a D1 database in
 * .wrangler/state, no Cloudflare Access, no TLS. It is for trying the thing
 * out and for development — never a deployment target.
 */
export async function dev({ slug, flags }) {
	const action = flags.get('down') ? 'down' : flags.get('logs') ? 'logs' : 'up';
	const dryRun = flags.has('dry-run');

	// A dry run is meant to show the plan, so a missing or stopped Docker is
	// reported and then stepped over rather than ending the run — otherwise
	// the one mode that explains what will happen is the one you cannot use
	// until everything is already working.
	const ready = await ensureDocker({ assumeYes: flags.has('yes'), dryRun });
	if (!ready && !dryRun) return 1;
	if (!ready) console.log('\n(continuing anyway to show the plan)');

	if (action === 'down') {
		// --clean also drops the volumes, which is what a half-created or
		// stale dependency volume needs. It deletes the local database too:
		// this is a rehearsal space, so that is recoverable by re-seeding.
		const args = ['compose', '-f', resolve(DOCKER_DIR, 'docker-compose.yml'), 'down'];
		if (flags.has('clean')) args.push('--volumes');
		run('docker', args, { dryRun });
		if (flags.has('clean')) console.log('\nVolumes removed. The next `dev` reinstalls dependencies and re-seeds.');
		return 0;
	}
	if (action === 'logs') {
		run('docker', ['compose', '-f', resolve(DOCKER_DIR, 'docker-compose.yml'), 'logs', '-f'], { dryRun });
		return 0;
	}

	// ── Brand ────────────────────────────────────────────────────
	const { brand, dir } = readBrand(slug);
	const problems = validate(brand);
	if (problems.length) {
		console.error(`\n✗ ${dir}/brand.json is not valid:`);
		for (const p of problems) console.error(`   - ${p}`);
		return 1;
	}

	const apiPort = flags.get('api-port') ?? '8787';
	const webPort = flags.get('web-port') ?? '4321';
	const adminPort = flags.get('admin-port') ?? '4322';

	// ── Brand tokens ─────────────────────────────────────────────
	console.log(`\nBuilding ${brand.identity.name} locally`);
	run('node', [
		resolve(REPO_ROOT, 'packages/brand/src/generate.mjs'),
		'--brand', resolve(dir, 'brand.json'),
		'--out', resolve(appDir('web'), 'src/styles'),
	], { dryRun });

	// ── Environment for the containers ───────────────────────────
	const envPath = resolve(DOCKER_DIR, '.env');
	const existing = existsSync(envPath) ? parseEnvFile(readFileSync(envPath, 'utf8')) : {};

	// A per-machine value, generated once and reused, so it never has to be
	// invented by hand or copied from documentation. Computed before the
	// wrangler config below, which needs it too.
	const bypass = existing.ADMIN_DEV_BYPASS || randomBytes(24).toString('hex');

	// ── Local API config ─────────────────────────────────────────
	// A local wrangler.jsonc, kept separate from any real one so running the
	// local stack can never touch a church's deployed database.
	//
	// The entry point and runtime settings are read from the deployment
	// template rather than repeated here. They were repeated, and drifted:
	// the Worker's entry moved from src/index.ts to src/worker.ts and this
	// file kept pointing at a path that no longer existed.
	const template = parseJsonc(readFileSync(resolve(appDir('api'), 'wrangler.jsonc.example'), 'utf8'));
	const localConfig = resolve(appDir('api'), 'wrangler.local.jsonc');
	if (!dryRun) {
		// Rewritten every run, not written once. A file written once outlives
		// the code that generated it: this one kept pointing at an entry
		// point that had been renamed, and every container start failed until
		// someone deleted it by hand. It is generated and gitignored, so
		// there is nothing in it worth preserving across runs.
		writeFileSync(localConfig, localWranglerConfig({ slug, adminPort, template, adminDevBypass: bypass }));
		console.log(`  wrote ${localConfig}`);

		// A config naming a file that does not exist fails inside the
		// container, where the error is easy to miss. Catch it here.
		if (!existsSync(resolve(appDir('api'), template.main))) {
			console.error(`\n✗ apps/api/${template.main} does not exist, but wrangler.jsonc.example names it as the entry point.`);
			return 1;
		}
	}

	const lines = [
		'# Generated by `churchkit dev`. Local only — do not deploy from this.',
		'# Gitignored: it carries whatever credentials you are testing with.',
		`API_PORT=${apiPort}`,
		`WEB_PORT=${webPort}`,
		`ADMIN_PORT=${adminPort}`,
		'',
		'# Skips Cloudflare Access for requests whose own hostname is loopback,',
		'# which a deployed Worker\'s never is. Never run `wrangler secret put`',
		'# with this name — see apps/api/src/lib/localAdmin.ts.',
		`ADMIN_DEV_BYPASS=${bypass}`,
		'',
		'# Add any credentials you want to exercise locally, e.g.',
		'# YOUTUBE_API_KEY=... — anything unset simply stays switched off.',
	];
	for (const [key, value] of Object.entries(existing)) {
		if (['API_PORT', 'WEB_PORT', 'ADMIN_PORT', 'ADMIN_DEV_BYPASS'].includes(key)) continue;
		lines.push(`${key}=${value}`);
	}

	if (!dryRun) {
		mkdirSync(DOCKER_DIR, { recursive: true });
		writeFileSync(envPath, lines.join('\n') + '\n');
		console.log(`  wrote ${envPath}`);
	}

	// ── Start ────────────────────────────────────────────────────
	const compose = ['compose', '-f', resolve(DOCKER_DIR, 'docker-compose.yml')];

	// Start from nothing when asked, for a volume left in a half-created
	// state by an earlier failed run.
	if (flags.has('clean')) {
		console.log('\nRemoving existing containers and volumes');
		run('docker', [...compose, 'down', '--volumes'], { dryRun });
	}
	const result = run('docker', [...compose, 'up', '--build', ...(flags.has('attach') ? [] : ['-d'])], { dryRun });
	if (!result.ok && !result.dryRun) {
		// Compose reports that a container exited, never why. The reason is
		// in that container's log, so print it here rather than leaving
		// someone to discover `docker compose logs` on their own.
		console.error('\n─── the API container\'s last output ───');
		run('docker', [...compose, 'logs', '--no-color', '--tail=40', 'api'], {});
		console.error('\nFull logs: churchkit dev ' + slug + ' --logs');
		return 1;
	}

	// Seed once the API is up, so the local stack shows this church rather
	// than an empty database. Re-running `dev` re-applies identity from
	// brand.json and leaves any content added in the admin panel alone.
	if (!flags.has('no-seed') && !dryRun) {
		console.log('\nWaiting for the API to come up…');
		const healthy = await waitForApi(apiPort);
		if (!healthy) {
			console.error('  The API did not become healthy. Check: churchkit dev ' + slug + ' --logs');
			return 1;
		}
		console.log('\nSeeding the local database');
		await seed({ slug, flags: withFlags(flags, ['local', ...(flags.has('example') ? ['example'] : [])]) });
	}

	if (!flags.has('attach')) {
		console.log(`
Running as ${brand.identity.name}:
  Website      http://localhost:${webPort}
  Admin panel  http://localhost:${adminPort}
  API          http://localhost:${apiPort}/api/capabilities

  churchkit dev ${slug} --example   also load starter pages and a carousel
  churchkit dev ${slug} --logs      follow output
  churchkit dev ${slug} --down      stop everything

Edit brand.json and re-run to update what the site shows. Pages and staff
you add in the admin panel are kept.
`);
	}
	return 0;
}
