import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { createInterface } from 'node:readline/promises';
import { appDir, resourceNames } from '../lib/paths.mjs';
import { SECRETS, groupedSecrets } from '../lib/secrets.mjs';
import { run } from '../lib/run.mjs';

/**
 * The annotated file: every known secret, grouped, each with where its value
 * comes from. `values` fills in what's known so far — `--init` calls this
 * with nothing (an empty template), the wizard calls it with what was just
 * gathered (a filled-in file), so both write in the exact same shape and
 * either can pick up where the other left off.
 */
function renderSecretsFile(values = {}) {
	const lines = [
		'# Generated by `churchkit secrets`. Fill in what you have and leave the',
		'# rest blank — a credential you skip simply turns its feature off.',
		'# This file is gitignored; nothing here is meant to reach the repository.',
		'',
	];
	for (const [group, entries] of groupedSecrets()) {
		lines.push(`# ── ${group} ${'─'.repeat(Math.max(0, 58 - group.length))}`);
		for (const s of entries) {
			lines.push(`# ${s.name} — ${s.feature}`);
			lines.push(`#   ${s.where}`);
			lines.push(`${s.name}=${values[s.name] ?? ''}`);
			lines.push('');
		}
	}
	return lines.join('\n');
}

/**
 * Push a church's credentials to its API Worker.
 *
 * Reads a local env-format file, never the repository. Values go straight
 * to Cloudflare via `wrangler secret bulk` and are not echoed, written
 * anywhere, or kept — the file stays on the operator's machine and is
 * gitignored.
 *
 * A blank value is skipped rather than set to an empty string, because the
 * API treats an empty credential as absent anyway and an empty secret is
 * harder to notice than a missing one.
 *
 * `--init` writes the annotated template to disk instead of pushing —
 * a starting point to fill in, with where each value comes from noted
 * right next to it, rather than a bare `KEY=` line that says nothing about
 * which of four or five unrelated dashboards it comes from.
 *
 * `--status` doesn't touch the file at all: it lists which of the known
 * secrets are actually set on the deployed Worker right now (names only —
 * Cloudflare never returns values), so gathering credentials over several
 * sessions has a way to check progress against reality instead of a local
 * file that may be stale or already pushed.
 *
 * `--wizard` prompts for each secret one at a time instead of requiring an
 * editor: a group can be skipped outright ("no Planning Center account"),
 * an already-filled value is kept by pressing Enter, and it ends by asking
 * whether to push what was just gathered — no separate invocation needed.
 */
export async function secrets({ slug, flags }) {
	const dryRun = flags.has('dry-run');
	const file = resolve(process.cwd(), flags.get('file') ?? `.secrets.${slug}`);

	if (flags.has('status')) return secretsStatus(slug);

	if (flags.has('wizard')) return secretsWizard({ slug, file, dryRun });

	if (flags.has('init')) {
		if (existsSync(file) && !flags.has('force')) {
			console.log(`\n${file} already exists — pass --force to overwrite it.`);
			return 1;
		}
		writeFileSync(file, renderSecretsFile());
		console.log(`\nWrote ${file}`);
		console.log(`Fill in what you have, then: churchkit secrets ${slug}`);
		console.log(`Prefer being prompted for each one instead: churchkit secrets ${slug} --wizard`);
		console.log(`Check what's already live at any point: churchkit secrets ${slug} --status`);
		return 0;
	}

	if (!existsSync(file)) {
		console.log(`\nNo secrets file at ${file}\n`);
		console.log(`Run \`churchkit secrets ${slug} --init\` to write an annotated template, or`);
		console.log('create one yourself in env format. Every line is optional — a credential');
		console.log('you leave out simply turns its feature off:\n');
		for (const [group, entries] of groupedSecrets()) {
			console.log(`# ${group}`);
			for (const s of entries) console.log(`${s.name}=`);
			console.log('');
		}
		console.log(`Then: churchkit secrets ${slug} --file=<path>`);
		return 1;
	}

	const parsed = parseEnvFile(readFileSync(file, 'utf8'));
	return pushParsedSecrets({ slug, file, parsed, dryRun });
}

/**
 * Shared by the file-based push and the wizard's end-of-run prompt, so
 * "read a file and push it" and "push what was just gathered interactively"
 * can't drift into two different notions of what's safe to send — the same
 * ADMIN_DEV_BYPASS refusal and unknown-key filter apply either way.
 */
function pushParsedSecrets({ slug, file, parsed, dryRun }) {
	const known = new Set(SECRETS.map((s) => s.name));

	// Refused by name, not merely absent from the known list, so the reason
	// is explained rather than looking like a typo.
	if ('ADMIN_DEV_BYPASS' in parsed) {
		console.error('\n✗ ADMIN_DEV_BYPASS is for local development and must never be deployed.');
		console.error('  It belongs in docker/.env, which `churchkit dev` writes. Remove it from');
		console.error(`  ${file} and try again.`);
		return 1;
	}

	const unknown = Object.keys(parsed).filter((k) => !known.has(k));
	if (unknown.length) {
		console.log(`\n! Ignoring ${unknown.length} unrecognised key(s): ${unknown.join(', ')}`);
		console.log('  (a typo here would otherwise look like a working credential)');
		for (const key of unknown) delete parsed[key];
	}

	const set = Object.entries(parsed).filter(([, v]) => v !== '');
	if (!set.length) {
		console.log(`\nNothing to push — every value in ${file} is blank.`);
		return 1;
	}

	console.log(`\nPushing ${set.length} secret(s) to ${resourceNames(slug).apiWorker}`);
	for (const [name] of set) console.log(`  ${name}`);

	if (dryRun) {
		console.log('\n(dry run — nothing sent)');
		return 0;
	}

	// `secret bulk` reads JSON on stdin, which keeps values off the command
	// line where they would land in shell history and process listings.
	const payload = JSON.stringify(Object.fromEntries(set));
	const result = run('sh', ['-c', `printf %s ${shellQuote(payload)} | npx wrangler secret bulk`], {
		cwd: appDir('api'),
	});
	return result.ok ? 0 : 1;
}

/** `churchkit secrets <slug> --wizard` — prompt for each secret, group by group. */
async function secretsWizard({ slug, file, dryRun }) {
	const existing = existsSync(file) ? parseEnvFile(readFileSync(file, 'utf8')) : {};
	const values = { ...existing };

	const rl = createInterface({ input: process.stdin, output: process.stdout });
	const ask = (q) => rl.question(q);

	console.log(`\nGathering credentials for ${slug}. Enter skips a field and keeps whatever`);
	console.log('was already there (blank if nothing was); "-" clears a field that was set.');
	console.log('Typing "skip" at a group answers Enter for every field left in it.\n');

	try {
		for (const [group, entries] of groupedSecrets()) {
			const already = entries.filter((s) => values[s.name]).length;
			const header = await ask(
				`── ${group} (${already}/${entries.length} already set) — configure now? [Y/n/skip] `
			);
			if (/^(n|no|skip)/i.test(header.trim())) {
				console.log('  skipped\n');
				continue;
			}

			for (const s of entries) {
				const current = values[s.name];
				console.log(`\n${s.name} — ${s.feature}`);
				console.log(`  ${s.where}`);
				if (current) console.log(`  current: ${maskValue(current)}`);
				const prompt = current ? '  new value (Enter to keep, "-" to clear): ' : '  value (Enter to skip): ';
				const answer = (await ask(prompt)).trim();
				if (answer === '-') values[s.name] = '';
				else if (answer !== '') values[s.name] = answer;
				// blank answer: leave `current` (or the absence of one) as-is

				// After every field, not just at the end: a Ctrl+C mid-group
				// used to lose everything typed in the entire session, which
				// is exactly the failure mode this file exists to prevent.
				writeFileSync(file, renderSecretsFile(values));
			}
			console.log('');
		}
	} catch (e) {
		// readline/promises rejects the pending question() on Ctrl+C rather
		// than throwing a recognisable AbortError type, so this catches
		// anything rather than matching a specific class. Whatever was
		// answered before the interruption is already on disk (see above) —
		// this just says so, instead of the generic top-level "✗ <message>"
		// cli.mjs would otherwise print for an error with nothing to add.
		console.log(`\n\nInterrupted. Everything answered so far is saved to ${file}.`);
		console.log(`Resume any time: churchkit secrets ${slug} --wizard`);
		return 1;
	} finally {
		rl.close();
	}

	writeFileSync(file, renderSecretsFile(values));
	const filledCount = Object.values(values).filter(Boolean).length;
	console.log(`Saved ${filledCount}/${SECRETS.length} values to ${file}.`);

	const rl2 = createInterface({ input: process.stdin, output: process.stdout });
	const pushNow = await rl2.question(`\nPush to ${resourceNames(slug).apiWorker} now? [y/N] `);
	rl2.close();
	if (!/^y/i.test(pushNow.trim())) {
		console.log(`\nNot pushed. Review ${file}, then: churchkit secrets ${slug}`);
		return 0;
	}

	return pushParsedSecrets({ slug, file, parsed: values, dryRun });
}

/** First 2 and last 2 characters, so a value on screen is recognisable without being readable. */
function maskValue(value) {
	if (value.length <= 6) return '••••••';
	return `${value.slice(0, 2)}${'•'.repeat(Math.min(value.length - 4, 20))}${value.slice(-2)}`;
}

/** `churchkit secrets <slug> --status` — what's actually live, grouped, against the known list. */
function secretsStatus(slug) {
	const worker = resourceNames(slug).apiWorker;
	console.log(`\nChecking ${worker}…`);

	const result = run('npx', ['wrangler', 'secret', 'list'], { cwd: appDir('api'), capture: true });
	if (!result.ok) {
		console.error(`\n✗ Could not list secrets on ${worker}. Is it deployed yet?`);
		return 1;
	}

	let live;
	try {
		live = new Set(JSON.parse(result.stdout).map((s) => s.name));
	} catch {
		console.error('\n✗ Could not parse `wrangler secret list` output.');
		return 1;
	}

	console.log('');
	let setCount = 0;
	for (const [group, entries] of groupedSecrets()) {
		console.log(`${group}`);
		for (const s of entries) {
			const isSet = live.has(s.name);
			if (isSet) setCount++;
			console.log(`  ${isSet ? '✓' : '·'} ${s.name}${isSet ? '' : ` — ${s.feature}`}`);
		}
	}
	console.log(`\n${setCount}/${SECRETS.length} set on the deployed Worker.`);
	console.log('(Names only — Cloudflare never returns values, so this cannot tell you');
	console.log(' whether a set secret is a *correct* one. For that: the admin panel\'s');
	console.log(' System Health page, which actually calls each provider.)');
	return 0;
}

/** Minimal env-file parser: KEY=value, # comments, blank lines. */
export function parseEnvFile(text) {
	const out = {};
	for (const line of text.split('\n')) {
		const trimmed = line.trim();
		if (!trimmed || trimmed.startsWith('#')) continue;
		const eq = trimmed.indexOf('=');
		if (eq === -1) continue;
		const key = trimmed.slice(0, eq).trim();
		let value = trimmed.slice(eq + 1).trim();
		if (
			(value.startsWith('"') && value.endsWith('"') && value.length > 1) ||
			(value.startsWith("'") && value.endsWith("'") && value.length > 1)
		) {
			value = value.slice(1, -1);
		}
		if (key) out[key] = value;
	}
	return out;
}

function shellQuote(value) {
	return `'${String(value).replace(/'/g, `'\\''`)}'`;
}
