#!/usr/bin/env node
/**
 * ChurchKit brand token generator.
 *
 * Reads one brand.json and emits the per-deployment theme files the apps
 * consume:
 *
 *   tokens.css   CSS custom properties  → apps/web, apps/admin
 *   theme.ts     typed token module     → apps/mobile
 *   brand.json   normalised copy        → apps/api (seeds `settings`)
 *
 * Nothing church-specific is ever committed to an app. A deployment runs
 * this against its own brand.json at build time.
 *
 * Usage:
 *   node generate.mjs --brand path/to/brand.json --out path/to/outdir
 */

import { readFileSync, mkdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { validate } from './validate.mjs';

function parseArgs(argv) {
	const args = { brand: null, out: null };
	for (let i = 0; i < argv.length; i++) {
		if (argv[i] === '--brand') args.brand = argv[++i];
		else if (argv[i] === '--out') args.out = argv[++i];
	}
	if (!args.brand || !args.out) {
		console.error('usage: generate.mjs --brand <brand.json> --out <dir>');
		process.exit(2);
	}
	return args;
}

/** camelCase token name → --kebab-case custom property. */
const kebab = (s) => s.replace(/[A-Z]/g, (c) => '-' + c.toLowerCase());

export function toCss(brand) {
	const c = brand.colors;
	const f = brand.fonts;
	const lines = Object.entries(c).map(([k, v]) => `      --${kebab(k)}: ${v};`);
	return `/* Generated by @churchkit/brand from ${brand.slug}/brand.json — do not edit. */
:root {
${lines.join('\n')}

      --font-heading: ${f.heading.stack};
      --font-body: ${f.body.stack};
      --font-display: ${f.display.stack};
}
`;
}

export function toMobileTheme(brand) {
	const c = brand.colors;
	const m = brand.fonts.mobile;
	const entry = (o) => Object.entries(o).map(([k, v]) => `  ${k}: '${v}',`).join('\n');
	return `// Generated by @churchkit/brand from ${brand.slug}/brand.json — do not edit.
// Regenerate with: npm run brand:build

export const Colors = {
${entry(c)}
} as const;

export const Fonts = {
${entry(m)}
} as const;

export const FontSizes = {
  xs: 11, sm: 13, base: 15, md: 17, lg: 20, xl: 24, '2xl': 30, '3xl': 38,
} as const;

export const Spacing = {
  xs: 4, sm: 8, md: 16, lg: 24, xl: 32, '2xl': 48,
} as const;

export const Radius = { sm: 6, md: 12, lg: 20, full: 999 } as const;

export const Shadow = {
  sm: { shadowColor: '#000', shadowOffset: { width: 0, height: 1 }, shadowOpacity: 0.08, shadowRadius: 3, elevation: 2 },
  md: { shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.12, shadowRadius: 8, elevation: 4 },
} as const;

export type ColorToken = keyof typeof Colors;
`;
}

function main() {
	const { brand: brandPath, out } = parseArgs(process.argv.slice(2));
	const abs = resolve(process.cwd(), brandPath);
	const brand = JSON.parse(readFileSync(abs, 'utf8'));

	const problems = validate(brand);
	if (problems.length) {
		console.error(`✗ ${brandPath} is not a valid brand file:`);
		for (const p of problems) console.error(`   - ${p}`);
		process.exit(1);
	}

	const outDir = resolve(process.cwd(), out);
	mkdirSync(outDir, { recursive: true });
	writeFileSync(resolve(outDir, 'tokens.css'), toCss(brand));
	writeFileSync(resolve(outDir, 'theme.ts'), toMobileTheme(brand));
	writeFileSync(resolve(outDir, 'brand.json'), JSON.stringify(brand, null, 2) + '\n');

	console.log(`✓ ${brand.identity.name} (${brand.slug})`);
	console.log(`  ${resolve(outDir, 'tokens.css')}`);
	console.log(`  ${resolve(outDir, 'theme.ts')}`);
	console.log(`  ${resolve(outDir, 'brand.json')}`);
}

if (import.meta.url === `file://${process.argv[1]}`) main();
