/**
 * Turn a brand file into the settings rows the apps actually read.
 *
 * brand.json holds a church's identity; the `settings` table is where the
 * website, admin panel and app look for it. Without something bridging the
 * two, a church fills in its brand file and then finds its own site still
 * showing the example church's name — which is exactly the gap this closes.
 *
 * Only settings derived from the brand are written. Content — pages, staff,
 * carousel — is a church's own, and belongs in the admin panel rather than
 * in anything generated.
 */

/** SQLite string literal, with quotes doubled. */
function quote(value) {
	return `'${String(value ?? '').replace(/'/g, "''")}'`;
}

/**
 * `service_times` is stored as a JSON blob, keyed by day. brand.json uses
 * the same shape, so this is a copy rather than a translation.
 */
function serviceTimesJson(brand) {
	const times = brand.serviceTimes ?? {};
	const cleaned = Object.fromEntries(
		Object.entries(times)
			.filter(([, entries]) => Array.isArray(entries) && entries.length > 0)
			.map(([day, entries]) => [day.toLowerCase(), entries])
	);
	return JSON.stringify(cleaned);
}

export function settingsFromBrand(brand) {
	const address = brand.contact?.address ?? {};
	// "100 Example Road, Springfield, IL 62701" — the postcode follows the
	// region with a space, not a comma, which is how a US address is written
	// and how a maps link expects to receive it.
	const cityLine = [
		[address.city, address.region].filter(Boolean).join(', '),
		address.postalCode,
	].filter(Boolean).join(' ');
	const oneLine = [address.street, cityLine].filter(Boolean).join(', ');

	return {
		church_name: brand.identity?.name ?? '',
		tagline: brand.identity?.tagline ?? '',
		phone: brand.contact?.phone ?? '',
		email: brand.contact?.email ?? '',
		address: oneLine,
		// Separate from `address`: a few short pieces of UI (the header's
		// worship-line, the footer's copyright) want "Leeds, AL" on its own,
		// and parsing it back out of the one-line address is fragile — commas
		// in a street name would break it silently.
		city: address.city ?? '',
		region: address.region ?? '',
		service_times: serviceTimesJson(brand),
		site_url: brand.urls?.web ?? '',
		church_center_url: brand.urls?.churchCenter ?? '',
		giving_url: brand.urls?.giving ?? '',
		timezone: brand.timezone ?? '',
		locale: brand.locale ?? '',
		social: JSON.stringify(brand.social ?? {}),
	};
}

/**
 * Settings SQL for a deployment.
 *
 * INSERT OR REPLACE, deliberately: re-running after editing brand.json
 * should update what the site shows. Settings a church edits only in the
 * admin panel — the welcome email, the nav override, the featured event —
 * are not touched, because they are not in the brand file.
 */
export function toSettingsSql(brand) {
	const rows = Object.entries(settingsFromBrand(brand));
	const values = rows.map(([key, value]) => `  (${quote(key)}, ${quote(value)})`).join(',\n');

	return `-- Generated by @churchkit/brand from ${brand.slug}/brand.json.
-- Church identity only. Pages, staff and carousel content are edited in the
-- admin panel and are never overwritten by this.
INSERT OR REPLACE INTO settings (key, value, updated_at) VALUES
${values.replace(/\)(,?)$/gm, ', unixepoch())$1')};
`;
}
