// Generated by @churchkit/brand from example-church/brand.json — do not edit.
// Regenerate with: npm run brand:build

export const Colors = {
  brand: '#2f4858',
  brandMid: '#5b7b8a',
  brandLight: '#8aa7b4',
  brandPale: '#dbe5ea',
  brandFaint: '#eef3f5',
  accent: '#c77d3a',
  accentPale: '#f7ece1',
  ink: '#1a1a18',
  inkSoft: '#4a4844',
  inkFaint: '#8a8680',
  surface: '#faf8f3',
  white: '#ffffff',
  border: '#e2ddd4',
  borderSoft: '#ede9e0',
  error: '#c0392b',
} as const;

export const Fonts = {
  heading: 'CormorantGaramond_600SemiBold',
  headingItalic: 'CormorantGaramond_600SemiBold_Italic',
  body: 'Roboto_400Regular',
  bodyMedium: 'Roboto_500Medium',
  bodyBold: 'Roboto_700Bold',
} as const;

export const FontSizes = {
  xs: 11, sm: 13, base: 15, md: 17, lg: 20, xl: 24, '2xl': 30, '3xl': 38,
} as const;

export const Spacing = {
  xs: 4, sm: 8, md: 16, lg: 24, xl: 32, '2xl': 48,
} as const;

export const Radius = { sm: 6, md: 12, lg: 20, full: 999 } as const;

export const Shadow = {
  sm: { shadowColor: '#000', shadowOffset: { width: 0, height: 1 }, shadowOpacity: 0.08, shadowRadius: 3, elevation: 2 },
  md: { shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.12, shadowRadius: 8, elevation: 4 },
} as const;

export type ColorToken = keyof typeof Colors;
